### PR TITLE
Add sqlite to travis

### PR DESCRIPTION
**Pull request by jonasschneider**
Actually I just want to see the Travis results ;)
Locally for me, the tests all passed, except for a strange glitch that needed clearing some tables (see commit).

Anyone care to take a look at this?

### CODE REVIEW

**Comment by titanous** [comment]
Nifty. The main thing to watch out for is that we were planning to use the Postgres Array type, but I think we should consider working around it (currently array columns are serialized into array format, but the column type isn't Array).

**Comment by titanous** [comment]
Looks like travis is borked, you might try pushing to this branch again to force a rerun.

**Comment by jonasschneider** [comment]
Ah, okay. I was checking out Sqlite as a workaround for easy multihoming, where isolation is needed between every entity. Creating postgres DBs for every user didn't seem that good to me. I will try and investigate other options for setting a 'global scope' with datamapper.

**Comment by titanous** [comment]
We're actually working on that right now, I'll have a patch in a couple of days that makes the schema multi-tenant.

**Comment by jonasschneider** [comment]
Oh, great!

**Comment by titanous** [comment]
So it looks like this pull request fundamentally breaks something in Travis, I've sent a message to them to figure out what's going on.

**Comment by titanous** [comment]
I just heard back from the Travis folks. Try wrapping the new environment variable in quotes, like this:

```
- "TEST_DATABASE_URL=sqlite::memory:"
```

**Comment by jonasschneider** [comment]
Lol, this time the build failed because GitHub was down shortly yesterday.

**Comment by jonasschneider** [comment]
Aw. the jruby build fails on this one because the box doesn't have JDBC installed. Sadly, I dont have any idea how a `before_script` that fixes it should look. Maven? Ant? Wget?

**Comment by titanous** [comment]
It needs to be special-cased like this due to a bug in DM: https://github.com/tent/tentd/blob/master/lib/tentd/model.rb#L1

http://rubygems.org/gems/jdbc-sqlite3

Check the 'scheme' of the database url, and the correct adapter if on JRuby.

**Comment by titanous** [comment]
@jonasschneider Check out fe63c2e10b0209bec77d092d999c46cde4b866f4. I added multi-tenant capability.

**Comment by jonasschneider** [comment]
Great job on the multi-tenant feature. I've added the `jdbc-sqlite3` gem to `spec_helper.rb` and to the Gemfile only since I figured you wouldn't want to depend on sqlite everywhere as postgres is the default. Under my local jruby, it's working now, let's see what Travis says.

**Pull request closed without merging**
